### ISSUE TITLE
dspdfviewer refuses to use second display

### ISSUE THREAD

**Issue by kaergel** [dannyedel/dspdfviewer#33] opened 2015-04-12 11:37 UTC
I received my new work machine this week and recognized dspdfviewer is not working as expected anymore. 
On my old machine a beamer/monitor was plugged in to a vga port and the vga-port was named VGA1 in xrandr. All i had to do is to configure my second monitor via xrandr and use dspdfviewer.
Using the new machine a beamer/monitor connected to the vga-port is named DP1 in xrandr. dspsdfviewer does not open the public presentation on the second monitor anymore. Instead it is opened on the same viewport like the presenter view. 
Is this related to the names randr is choosing for the displays? Is it possible to add an option which specifies the desired output name?

**Comment by dannyedel** [comment] 2015-04-23 07:04
No, dspdfviewer does not depend on XRandR's display names, so I doubt this is it (on my test machines, sometimes the outputs are named "VGA1", "DVI-I-1", "HDMI-0", "LVDS" and it never caused issues, so I don't think there's anything special about the name "DP1").
What it does is query [QApplication::desktop()][1] and ask for a desktop by number, then [move the window to the top-left corner of that screen, resize and request fullscreen][2] On all my test systems, the "Qt desktop" with number 0 is the one marked as "primary" in XRandR, so I'm using that for the presenter's window.

Please try a minimalistic XRandR command (it must contain "primary" on one monitor) such as
```
xrandr --output LVDS --primary --preferred --output DP1 --preferred --right-of LVDS
```

(obviously, replacing LVDS with your internal and DP1 with your external monitor) and try launching dspdfviewer again.

If this does not solve it, please post the complete output of `xrandr` (please encase it in triple-backticks for github) and give details on your operation environment (type of machine, desktop environment, window manager, which OS are you using, did you use one of my binaries or compile from source, if so which compiler did you use, version of Qt on your system) and I will try to reproduce the problem.

[1]: http://doc.qt.io/qt-5/qapplication.html#desktop
[2]: https://github.com/dannyedel/dspdfviewer/blob/fad7cffcfeacd29ddb45b6c43444131c32d4160e/pdfviewerwindow.cpp#L85-L88

**Comment by dannyedel** [comment] 2015-07-27 11:40
@kaergel, in the meantime I've released (which also means re-built against current libraries) version 1.12. Can you please confirm that the problem still persists in the current version, and please post the full information I've requested in my previous comment. Especially without operating system and how you installed it (binary, source) I can't reproduce anything.

In case the problem doesn't exist anymore, please close the ticket.

**Comment by dannyedel** [comment] 2015-08-27 13:36
This ticket has gone a month in the need-more-info & cannot-reproduce states. I'm assuming the problem doesn't exist anymore.

I'll close the ticket, please reopen and provide requested information if the problem still exists.

**Closed by dannyedel** 2015-08-27 13:36 UTC
Labels: bug, cannot-reproduce, need-more-info
